build: fix build failure with ubuntu
Ubuntu reports below error:

    ctrl.c:52:9: error: ignoring return value of 'read' declared with
    attribute 'warn_unused_result' [-Werror=unused-result]
       52 |         read(fd, &expirations, sizeof(expirations));
          |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Yuanhan Liu <liuyuanhan.131@bytedance.com>