build: fix build failure with ubuntu 20.04
While building with Ubuntu 20.04 (gcc 9), there are quite a few errors
like below:

    tpad_sock.c:91:3: error: ignoring return value of ‘symlink’, declared
    with attribute warn_unused_result [-Werror=unused-result]
       91 |   symlink(archive_path(&ctx, id), tpad.sock_file);
          |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

There are also quite a few of them for the unit test build. I don't
bother to fix it, therefore, the -Wno-unused-result cflag is appended.

Signed-off-by: Yuanhan Liu <liuyuanhan.131@bytedance.com>